In [1]:
import numpy as np

In [2]:
A = np.array([[2, 3], [5, 7], [11, 13]])
B = np.array([[1, 3], [2, 1]])
C = np.array([[3, 1], [4, 2]])

El código que aparece a continuación realiza multiplicaciones de matrices utilizando arreglos de NumPy. Primero, se definen tres matrices: `A`, `B` y `C`. Luego, se calculan dos productos matriciales:

- `ABC = A.dot(B.dot(C))`: Multiplica primero las matrices `B` y `C`, y luego multiplica el resultado por la matriz `A`.
- `AB_C = A.dot(B).dot(C)`: Multiplica primero las matrices `A` y `B`, y luego multiplica el resultado por la matriz `C`.

En este caso, ambos métodos producen el mismo resultado porque la multiplicación de matrices es asociativa, es decir, el orden de las operaciones no afecta el resultado final siempre que la secuencia de las matrices sea la misma.

In [3]:
ABC =A.dot(B.dot(C))
ABC

array([[ 60,  26],
       [145,  63],
       [295, 129]])

In [4]:
AB_C = A.dot(B).dot(C)
AB_C

array([[ 60,  26],
       [145,  63],
       [295, 129]])

El siguiente bloque de código explora la propiedad distributiva de la multiplicación de matrices utilizando NumPy. Se calculan dos resultados:

- `D = A.dot(B + C)`: Primero se suman las matrices `B` y `C`, y luego se multiplica el resultado por la matriz `A`.
- `E = (A.dot(B)) + (A.dot(C))`: Se multiplica la matriz `A` por `B` y por `C` por separado, y luego se suman los resultados.

Ambos métodos deben producir el mismo resultado, ya que la multiplicación de matrices es distributiva respecto a la suma:  
**A · (B + C) = (A · B) + (A · C)**.  
Esto se puede verificar comparando los valores de `D` y `E`.


In [5]:
#Distributiva
D = A.dot(B + C)
E = (A.dot(B)) + (A.dot(C))

In [6]:
D

array([[ 26,  17],
       [ 62,  41],
       [122,  83]])

In [7]:
E

array([[ 26,  17],
       [ 62,  41],
       [122,  83]])

In [8]:
D == E

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

El siguiente bloque de código explora la propiedad conmutativa de la multiplicación de matrices utilizando NumPy. Se calculan dos resultados:

- `F = B.dot(C)`: Multiplica la matriz `B` por la matriz `C`.
- `G = C.dot(B)`: Multiplica la matriz `C` por la matriz `B`.

En este caso, los resultados de `F` y `G` son diferentes, lo que demuestra que la multiplicación de matrices **no es conmutativa**:  
**B · C ≠ C · B**.  
Esto se puede verificar comparando los valores de `F` y `G`.

In [9]:
#Conmutativa
F = B.dot(C)

In [10]:
G = C.dot(B)

In [11]:
F == G

array([[False, False],
       [False, False]])

In [12]:
F

array([[15,  7],
       [10,  4]])

In [13]:
G

array([[ 5, 10],
       [ 8, 14]])