In [1]:
import numpy as np

In [2]:
A = np.array([[2, 3], [5, 7], [11, 13]])
B = np.array([[1, 3], [2, 1]])

In [3]:
A

array([[ 2,  3],
       [ 5,  7],
       [11, 13]])

In [4]:
B

array([[1, 3],
       [2, 1]])

In [5]:
AB_T = A.dot(B).T

In [6]:
B_tA_t = B.T.dot(A.T)

In [7]:
AB_T == B_tA_t

array([[ True,  True,  True],
       [ True,  True,  True]])