In [1]:
import numpy as np

In [2]:
identidad = np.eye(4)
print(identidad)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [4]:
vector = np.array([[2], [3], [5], [7]])
print(identidad.dot(vector))

[[2.]
 [3.]
 [5.]
 [7.]]


In [5]:
print(vector)

[[2]
 [3]
 [5]
 [7]]


In [6]:
A = np.array([[1, 0, 1], [0, 1, 1], [-1, 1, 1]])
A

array([[ 1,  0,  1],
       [ 0,  1,  1],
       [-1,  1,  1]])

In [7]:
inversa_A = np.linalg.inv(A)

In [8]:
print(inversa_A)

[[ 0.  1. -1.]
 [-1.  2. -1.]
 [ 1. -1.  1.]]


In [9]:
print(A.dot(inversa_A))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
