In [1]:
import numpy as np

In [2]:
matriz = np.array([[1, 0, 0], 
                   [0, 1, 0],
                   [0, 0, 1]])

print(matriz)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [3]:
print(matriz[:, 0].dot(matriz[:,1]))

0


In [4]:
print(matriz[:, 0].dot(matriz[:, 2]))

0


In [5]:
print(matriz[:, 1].dot(matriz[:, 2]))

0


In [6]:
print(np.linalg.norm(matriz[:, 0]))
print(np.linalg.norm(matriz[:, 1]))
print(np.linalg.norm(matriz[:, 2]))

1.0
1.0
1.0


In [7]:
A = np.array([[np.cos(100), -np.sin(100)],
              [np.sin(100), np.cos(100)]])
print(A)

[[ 0.86231887  0.50636564]
 [-0.50636564  0.86231887]]


In [8]:
print(np.linalg.norm(A[0,:]))
print(np.linalg.norm(A[1,:]))
print(np.linalg.norm(A[:,0]))
print(np.linalg.norm(A[:,1]))

0.9999999999999999
0.9999999999999999
0.9999999999999999
0.9999999999999999
