In [1]:
import numpy as np

In [3]:
matriz = np.array([[1, 0, 0], 
                   [0, 1, 0],
                   [0, 0, 1]])

print(matriz)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [4]:
print(matriz[:, 0].dot(matriz[:,1]))

0


In [5]:
print(matriz[:, 0].dot(matriz[:, 2]))

0


In [6]:
print(matriz[:, 1].dot(matriz[:, 2]))

0


In [7]:
print(np.linalg.norm(matriz[:, 0]))
print(np.linalg.norm(matriz[:, 1]))
print(np.linalg.norm(matriz[:, 2]))

1.0
1.0
1.0
