## Debugging operaciones con tensores

Cuando trabajamos con tensores y las operaciones resultan no validas tendremos estos tres problemas mas comunes:
1. El tamaño o forma
2. El datatype
3. El device (dispositivo) en la que se encuentra el tensor

La forma (shape) te dice como estan organizados los elementos dentro del tensor

In [4]:
import torch
print(torch.__version__)

2.5.1+cu121


In [13]:
scalar = torch.tensor(2.0)
vector = torch.tensor([1.0, 2.0, 3.0])
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])
t5 = torch.randn(5, 2, 3)

In [14]:
print(f"La shape de la matriz es {matrix.shape}")
print(f"La shape de t5 es {t5.shape}")

La shape de la matriz es torch.Size([2, 3])
La shape de t5 es torch.Size([5, 2, 3])


Tambien podemos conocer la dimension de un tensor

In [15]:
print(f"La shape de la matriz es {matrix.ndim}")
print(f"La shape de t5 es {t5.ndim}")


La shape de la matriz es 2
La shape de t5 es 3


In [17]:
print(f"El tensor matriz tiene elementos de tipo: {matrix.dtype}")

El tensor matriz tiene elementos de tipo: torch.int64


In [18]:
matriz_float32 = torch.tensor([[3.1, 3.2], [3.3, 3.4]])
matriz_uint64 = torch.tensor([[3, 3], [3, 3]])

# matriz_float32.dtype, matriz_uint64.dtype

(matriz_float32 + matriz_uint64).dtype

torch.float32

Si es necesario cambiar el tipo de dato lo podemos realizar de la siguiente manera

In [19]:
matriz_uint64.to(torch.float)

tensor([[3., 3.],
        [3., 3.]])

Tenemos que tener en cuenta el dispositivo para que nuestro tensor este preparado. No podmeos operar con un tensor diseñado para GPU (CUDA) y uno para CPU

In [21]:
matriz_uint64.device

device(type='cpu')

In [22]:
torch.cuda.is_available()

True

In [23]:
if torch.cuda.is_available():
    matriz_unit64_cuda = matriz_uint64.to(torch.device("cuda"))

    print(matriz_unit64_cuda, matriz_unit64_cuda.type())
    print(matriz_unit64_cuda.to("cpu", torch.float32))


tensor([[3, 3],
        [3, 3]], device='cuda:0') torch.cuda.LongTensor
tensor([[3., 3.],
        [3., 3.]])


## 1.2 Interaccion con Numpy

Convierte el tensor a NumPy

In [25]:
matriz = torch.ones(2,2)
type(matriz.numpy())

numpy.ndarray

In [26]:
import numpy as np

Podemos convertir tambien de NumPy a PyTorch y el type se mantiene

In [27]:
vector = np.ones(5)
torch.from_numpy(vector).dtype

torch.float64

### Operaciones con tensores


Primero se crean algunos tensores en PyTorch:

In [28]:
# Crear un tensor de ceros con un shape de (3, 4)
zeros_tensor = torch.zeros((3, 4))

# Crear un tensor de unos con un shape de (3, 4)
ones_tensor = torch.ones((3, 4))

# Crear un tensor de valores aleatorios con un shape de (2, 2)
random_tensor = torch.randn((4))

In [30]:
random_tensor

tensor([ 1.5996, -1.6714, -0.2997,  0.2600])

ya con estos datos creados se realizan operaciones "element-wise"

In [32]:
# add two tensors element-twise
added_tensor = zeros_tensor + ones_tensor

# subtract two tensors element-twise
substracted_tensor = zeros_tensor - ones_tensor

# multiply two tensors element-wise
multiplied_tensor = zeros_tensor * ones_tensor

# divide two tensos element-wise
divided_tensor = random_tensor / ones_tensor

In [33]:
divided_tensor

tensor([[ 1.5996, -1.6714, -0.2997,  0.2600],
        [ 1.5996, -1.6714, -0.2997,  0.2600],
        [ 1.5996, -1.6714, -0.2997,  0.2600]])

Multiplicacion de matrices

In [35]:
matrix1 = torch.randn(2, 3)
matrix2 = torch.randn(3, 2)

print(f"Matrix1 shape: {matrix1.shape}")
print(f"Matrix2 shape: {matrix2.shape}")

torch.matmul(matrix1, matrix2).shape

Matrix1 shape: torch.Size([2, 3])
Matrix2 shape: torch.Size([3, 2])


torch.Size([2, 2])