In [2]:
import numpy as np
escalar = np.array(42)
print(type(escalar))
print(escalar)

<class 'numpy.ndarray'>
42


Vector

In [3]:
vector = np.array([30, 29, 35, 32, 33, 28, 42])
print(vector)

[30 29 35 32 33 28 42]


Matrices

In [4]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Arrays eb Numpy

In [5]:
array = np.array([[1, 2, 3], [4, 5, 6]])
print(array.ndim)
print(array.shape)
print(array.dtype)

2
(2, 3)
int64


In [6]:
array = np.array([10, 20, 30, 40, 50])
print(array[1])
print(array[-1])
print(array[1:4])
print(array[1:7])

20
50
[20 30 40]
[20 30 40 50]


INdezacion booleana

In [7]:
bool_index = array > 25
print(bool_index)

[False False  True  True  True]


In [8]:
array = np.random.randint(1, 10, size=(3,3))
print(array)
print(array[1,0])

[[3 6 2]
 [8 3 1]
 [2 3 2]]
8


Transformación de Arrays

In [9]:
array = np.arange(1,13)
reshaped_array = array.reshape(4,3)
print(array)
print(reshaped_array)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [10]:
def add(x, y):
    return x + y

def subtract(x, y):
    return x - y

def multiply(x, y):
    return x * y

def divide(x, y):
    if y == 0:
        return "Cannot divide by zero"
    return x / y

# Test the calculator functions
print("Addition: 10 + 5 =", add(10, 5))
print("Subtraction: 10 - 5 =", subtract(10, 5))
print("Multiplication: 10 * 5 =", multiply(10, 5))
print("Division: 10 / 5 =", divide(10, 5))

Addition: 10 + 5 = 15
Subtraction: 10 - 5 = 5
Multiplication: 10 * 5 = 50
Division: 10 / 5 = 2.0


Calculos Matriciales

In [12]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Add A and B
sum = A + B
print("Addition:")
print(sum)

Addition:
[[ 6  8]
 [10 12]]
