In [7]:
import numpy as np

In [8]:
arr = np.random.randint(1, 20, 10)
matriz = arr.reshape(2,5)
matriz

array([[14,  7,  9, 18, 11],
       [ 7, 18,  9,  8,  4]])

On the last code I created an array in a range of 20 numbers, and after that I create one matrix with ".reshape"

**Funciones principales de numpy**

Now we will watch what are the principal functions with numpy and their uses

In [12]:
print(arr)
arr.max()

[14  7  9 18 11  7 18  9  8  4]


18

In [13]:
print(matriz)
matriz.max()

[[14  7  9 18 11]
 [ 7 18  9  8  4]]


18

With ".max" we are going to obtain the number that has the high value 

Now if we want to introduce a parameter, like compare the lines and after that obtain the high value between this booth lines we will obtain the next answer

In [15]:
print(matriz)
matriz.max(0)

[[14  7  9 18 11]
 [ 7 18  9  8  4]]


array([14, 18,  9, 18, 11])

With the following command we will be able to see the distribution that we have in the array.
(We can explain this as the smallest value compared to the highest value and there we find this difference)
(esto lo podemos explicar como el valor mas pequeño comparado con el valor mas alto y ahi encontramos esta diferencia)

In [17]:
print(arr)
arr.ptp()

[14  7  9 18 11  7 18  9  8  4]


14

If we want to calculate the percentile which is the value which is in the medium in our array we folow thw following structure, and if we want to give an order to our array we use the command ".sort()"

In [18]:
np.percentile(arr, 50)

9.0

In [19]:
arr.sort()
arr

array([ 4,  7,  7,  8,  9,  9, 11, 14, 18, 18])