In [21]:
import numpy as np

On the following code we'll denerate an array in which this array will return us an aleatory numbers using one structure 3*2

In [40]:
arr = np.random.randint(1, 10, (3,2))
arr

array([[1, 7],
       [7, 9],
       [6, 6]])

Now if we use the comand "variableName.shape" this will return us or indicate us how many lines and colums we have 

In [23]:
arr.shape

(3, 2)

In [42]:
arr.reshape(1,6)

array([[1, 7, 7, 9, 6, 6]])

The last command (reshape) is use when we want to change the form of that arry, for example we can change the matriz

In [47]:
arr.reshape(6,1)

array([[1],
       [7],
       [7],
       [9],
       [6],
       [6]])