In [1]:
import numpy as np

**On the following code we will see the conditions**

In [3]:
arr = np.linspace(1,10,10, dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

If we take the name of the array and use the following step, we will obtein the number which are up or down than the indicate number

In [4]:
arr < 5

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [6]:
indices_cond = arr > 5
indices_cond

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

If we safe the result in a variable we can obtein the value as same as we check the position, next we will find the code

In [9]:
arr[indices_cond]

array([ 6,  7,  8,  9, 10], dtype=int8)