In [6]:
import numpy as np

In the next line of code we will define an alone array (0 dimension)

In [11]:
scalar = np.array(42)
print(scalar)

42


And if we want to validate the number of dimension in numpy we need to use the following instriction 
var_name.ndim

In [9]:
scalar.ndim

0

Now in the next line of code we will define an array of 1 dimension

In [12]:
vector = np.array([1, 2, 3])
print(vector)
vector.ndim

[1 2 3]


1

Now in the next line of code we will define an array of 2 dimension

In [13]:
matriz = np.array([[1, 2, 3], [4, 5, 6]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]]


2