In [6]:
import numpy as np

In [7]:
lista=[1,2] *2
lista

[1, 2, 1, 2]

In [12]:
arr = np.arange(0,10)
arr2 = arr.copy()

If we see, on the last code we created a list in where we wanted to multiplicate those numbers to 2, but the result was add those numbers and not mutiplicate, so we can fix that issue we can use numpy as we can will do in the following steps

In [14]:
print(arr)
print(arr * 2)

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]


So now if we can se each number *, 2 have the result as we wanted at the be beginning

And if we want to do an addition we only need to change to symbol and that going to retunt the addition

In [15]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

And this is the same with wathever mathematic ecuation  