In [1]:
import numpy as np

In the next line we will define an array

In [13]:
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

And if we define one property we will use the following syntax in where we will indicate that we want that array in a data type float

In [11]:
arr = np.array([1, 2, 3, 4], dtype='float64')
arr.dtype

dtype('float64')

In [12]:
arr

array([1., 2., 3., 4.])

Now, as we can see in the last line of code, our array is in float type

In [16]:
arr = arr.astype(np.float64)
arr

array([1., 2., 3., 4.])

The last line is other way about how we can change the data type

Now we are going to change the type of data for a bool in where we need to know that pyhon and numpy take the number 0 as a False and the rest as a True

In [18]:
arr = np.array([0, 1, 2, 3, 4, 5])
arr = arr.astype(np.bool_)
arr

array([False,  True,  True,  True,  True,  True])

If we want to define a string we only need to use the following sintax

In [19]:
arr = np.array([0, 1, 2, 3, 4, 5])
arr = arr.astype(np.str_)
arr

array(['0', '1', '2', '3', '4', '5'], dtype='<U21')

In the following link we can se all the data types
https://numpy.org/doc/stable/user/basics.types.html