In [2]:
import numpy as np

Scalar

In [3]:
x = np.array(42)
print(x.shape)
x.ndim

()


0

vector

In [4]:
x = np.array([42, 4, 5, 6, 7, 8])
print(x.shape)
x.ndim

(6,)


1

matriz

In [5]:
x = np.array([[42, 4, 5, 6, 7, 8], [66, 7, 8, 9, 10, 11]])
print(x.shape)
x.ndim

(2, 6)


2

tensor

In [6]:
x = np.array([[[42, 4, 5, 6, 7, 8],
               [66, 7, 8, 9, 10, 11]],
              [[1, 2, 3, 4, 5, 6],
               [7, 8, 9, 10, 11, 12]],
              [ [13, 14, 15, 16, 17, 18],
               [ 19, 20, 21, 22, 23, 24]]])
print(x.shape)
x.ndim

(3, 2, 6)


3

Reshape

In [7]:
x = np.array([[0, 1],
                [2, 3],
                [4, 5],
                [6, 7]            
])
x.shape

(4, 2)

In [8]:
x.reshape(8, 1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [9]:
x.reshape(1, 8)

array([[0, 1, 2, 3, 4, 5, 6, 7]])

In [10]:
x.reshape(2, 4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])