In [1]:
import numpy as np
escalar = np.array(42)
print(type(escalar))
print(escalar)

<class 'numpy.ndarray'>
42


Vector

In [5]:
vector = np.array([30, 29, 35, 32, 33, 28, 42])
print(vector)

[30 29 35 32 33 28 42]


Matrices

In [4]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Arrays eb Numpy

In [7]:
array = np.array([[1, 2, 3], [4, 5, 6]])
print(array.ndim)
print(array.shape)
print(array.dtype)

2
(2, 3)
int64
