In [7]:
import numpy as np

calificaciones_reales = np.array([5, 2])
calificaciones_modelo = np.array([4, 4])

print(calificaciones_reales)
print(calificaciones_modelo)

[5 2]
[4 4]


In [8]:
error = calificaciones_reales -calificaciones_modelo
print(error)

[ 1 -2]


In [9]:
porcentaje_ajuste = 0.1

ajuste = error * porcentaje_ajuste
print(ajuste)

[ 0.1 -0.2]


In [12]:
ventas_enero = np.array([
    [150, 200, 180],
    [120, 90, 100]
])

ventas_febrero = np.array([
    [130, 210, 190],
    [110, 80, 120]
])

print(ventas_enero)
print(ventas_febrero)

[[150 200 180]
 [120  90 100]]
[[130 210 190]
 [110  80 120]]


In [14]:
ventas_totales = ventas_enero + ventas_febrero
print(ventas_totales)

[[280 410 370]
 [230 170 220]]


In [15]:
bonificaciones = np.array([10, 15, 5])

ventas_con_bono = ventas_enero + bonificaciones
ventas_con_bono

array([[160, 215, 185],
       [130, 105, 105]])