In [2]:
import numpy as np

peliculas_features = np.array([
    [5, 2],
    [1, 5],
    [4, 4]
])

pesos_generos = np.array([
    [1.1, 0.4, 0.1],
    [0.2, 0.5, 1.2]
])

In [3]:
print(f"Shape pelicualas features {peliculas_features.shape}")
print(f"Shape pesos generos {pesos_generos.shape}")


Shape pelicualas features (3, 2)
Shape pesos generos (2, 3)


In [4]:
scores_prediccion = peliculas_features @ pesos_generos
print(f"Shape de la matriz de prediccion {scores_prediccion.shape}")
print(f"Matriz de scores (o nivel de confianza) para cada genero: {scores_prediccion}")

Shape de la matriz de prediccion (3, 3)
Matriz de scores (o nivel de confianza) para cada genero: [[5.9 3.  2.9]
 [2.1 2.9 6.1]
 [5.2 3.6 5.2]]


In [5]:
usuarios = np.array([
    [0.9, 0.2, 0.1, 0.8],
    [0.1, 0.8, 0.7, 0.2],
    [0.8, 0.7, 0.1, 0.1]
])

peliculas = np.array([
    [0.8, 0.1, 0.1, 0.9],
    [0.2, 0.9, 0.8, 0.1]
])

In [6]:
print(usuarios.shape)
print(peliculas.shape)

(3, 4)
(2, 4)


In [8]:
peliculas_transpuesta = peliculas.T
print(peliculas_transpuesta)
print(peliculas_transpuesta.shape)

[[0.8 0.2]
 [0.1 0.9]
 [0.1 0.8]
 [0.9 0.1]]
(4, 2)


In [9]:
matriz_similitud = usuarios @ peliculas_transpuesta
print(matriz_similitud)

[[1.47 0.52]
 [0.41 1.32]
 [0.81 0.88]]
