In [1]:
import numpy as np

I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [2]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(A @ I)

[[1. 2. 3.]
 [4. 5. 6.]]


In [3]:
M = np.array([
    [3, 1],
    [2, 2]
])

In [4]:
determinante = np.linalg.det(M)
print(determinante)

4.000000000000001


In [5]:
M_inversa = np.linalg.inv(M)
print(M_inversa)

[[ 0.5  -0.25]
 [-0.5   0.75]]


In [7]:
identidad = M @ M_inversa
print(np.round(identidad, 2))

[[1. 0.]
 [0. 1.]]
