In [1]:
import numpy as np
import matplotlib.pyplot as plt

X = np.array([
    [80, 3],
    [120, 3],
    [100, 2],
    [150, 4]
])

y = np.array([310, 390, 325, 530])
X_bias = np.c_[np.ones((4, 1)), X]

A_saludable = X_bias.T @ X_bias
b = X_bias.T @ y

In [4]:
pies2 = X[:, 0] * 10.764
X_enfermo = np.c_[X, pies2]
X_enfermo_bias = np.c_[np.ones((4, 1)), X_enfermo]

print(X_enfermo_bias)

[[1.00000e+00 8.00000e+01 3.00000e+00 8.61120e+02]
 [1.00000e+00 1.20000e+02 3.00000e+00 1.29168e+03]
 [1.00000e+00 1.00000e+02 2.00000e+00 1.07640e+03]
 [1.00000e+00 1.50000e+02 4.00000e+00 1.61460e+03]]


In [5]:
A_enfermo = X_enfermo_bias.T @ X_enfermo_bias
b = X_enfermo_bias.T @ y

In [6]:
determinante = np.linalg.det(A_enfermo)
print(determinante)

0.0


In [7]:
rango = np.linalg.matrix_rank(A_enfermo)
print(rango)

3
