In [1]:
import numpy as np

In [2]:
escalar = 5.679
vector = np.array([3,4,5,6])
matriz = np.array([[1,2],[3,4],[5,6]])
tensor = np.array([
    [[1,2,3,30],[4,5,6,31],[7,8,9,32]],
    [[11,12,13,33],[14,15,16,34],[17,18,19,35]],
    [[21,22,23,36],[24,25,26,37],[27,28,29,38]],
])

In [ ]:
# Transpose the matrix 'matriz' and print the result
matriz_t = matriz.T
print(matriz_t)

[[1 3 5]
 [2 4 6]]


In [6]:
matriz.shape

(3, 2)

In [7]:
matriz_t.shape

(2, 3)

### Repetimos el proceso pero ahora en este caso con el tensor

In [10]:
tensor_t = tensor.T
# Print the transposed tensor
tensor_t

array([[[ 1, 11, 21],
        [ 4, 14, 24],
        [ 7, 17, 27]],

       [[ 2, 12, 22],
        [ 5, 15, 25],
        [ 8, 18, 28]],

       [[ 3, 13, 23],
        [ 6, 16, 26],
        [ 9, 19, 29]],

       [[30, 33, 36],
        [31, 34, 37],
        [32, 35, 38]]])

In [9]:
tensor

array([[[ 1,  2,  3, 30],
        [ 4,  5,  6, 31],
        [ 7,  8,  9, 32]],

       [[11, 12, 13, 33],
        [14, 15, 16, 34],
        [17, 18, 19, 35]],

       [[21, 22, 23, 36],
        [24, 25, 26, 37],
        [27, 28, 29, 38]]])

### Proceso para la suma de matrices

In [13]:
A = np.array([[1,2],[3,4],[5,6]])
B = np.array([[6,5],[4,3],[2,1]])
C = A+B
print(A)
print(B)


[[1 2]
 [3 4]
 [5 6]]
[[6 5]
 [4 3]
 [2 1]]


In [14]:
print(C)

[[7 7]
 [7 7]
 [7 7]]
