In [6]:
import numpy as np

In [7]:
A = np.array([[3, 2], [4, 1]])
print(A)

[[3 2]
 [4 1]]


In [8]:
autovalores, autovectores = np.linalg.eig(A)

In [9]:
print(autovalores)
print(autovectores)

[ 5. -1.]
[[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


In [12]:
A_calc = autovectores.dot(np.diag(autovalores)).dot(np.linalg.inv(autovectores))

In [13]:
print(A_calc)

[[3. 2.]
 [4. 1.]]


In [15]:
A = np.array([[3, 2], [2, 3]])
print(A)

[[3 2]
 [2 3]]


In [16]:
print(A == A.T)

[[ True  True]
 [ True  True]]


In [17]:
autovalores, autovectores = np.linalg.eig(A)
print(autovalores)
print(autovectores)

[5. 1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
